---
title: "predicting_script"
author: "Andrew Ferreira"
date: "2/23/2022"
output: html_document
---

## Installing libraries

```{r Install library, include=FALSE}

#install.packages(c("dplyr", "tidyverse", "tidytext", "ggplot2", "forcats", "igraph", 
#                   "ggraph", "jsonlite", "tm", "parsnip", "tidymodels", "googlesheets4"))
library(dplyr)
library(tidytext)
library(ggplot2)
library(forcats)
library(igraph)
library(ggraph)
library(jsonlite)
library(parsnip) 
library(tidymodels)
library(tidyverse) 
library(tm)
library(googlesheets4)
```


## Uploading model and bigrams

```{r Load bigram and model}
bigrams <- read.csv("bigrams_top_1k.csv", header = TRUE)
model <- readRDS("final_model_UNK.rds")
```



```{r}
library(googlesheets4)
ss <- "https://docs.google.com/spreadsheets/d/1DqXv4iFTlEhzKViGO-d88xQMsPGqOWUId1IzHdps_kA/edit?resourcekey#gid=882919925"

google_sheet <- read_sheet(
  ss,
  range = "A:C"
  )

google_sheet_df <- as.data.frame(google_sheet)

reviews_to_classify <- google_sheet_df %>%
  mutate(row = row_number() + 1) %>%
  select(-`Carimbo de data/hora`) %>%
  filter(is.na(Classification))

# UNK
modeling_reviews <- reviews_to_classify %>%
  unnest_tokens(bigram, Review, token = "ngrams", n = 2) %>%
  separate(bigram, c("word1", "word2"), sep = " ") %>%
  filter(!word1 %in% stop_words$word) %>%
  filter(!word2 %in% stop_words$word) %>%
  unite(bigram, word1, word2, sep = " ") %>%
  mutate(finalBigram = if_else(
    bigram %in% bigrams$bigram, 
    bigram, "<UNK>")
    )


modeling_reviews_count <- modeling_reviews %>%
  group_by(row) %>%
  count(finalBigram, sort = TRUE)

modeling_reviews_m <- modeling_reviews_count %>%
  cast_dtm(row, finalBigram, n)

modeling_reviews_dtm <- data.frame(as.matrix(modeling_reviews_m)) 

modeling_reviews_dtm <- modeling_reviews_dtm %>%
  mutate(row = row.names(modeling_reviews_dtm))

modeling_reviews_dtm$row <- as.integer(modeling_reviews_dtm$row)

modeling_reviews_dtm <- modeling_reviews_dtm %>%
  left_join(reviews_to_classify)

#IM HERE -- HOW TO ENSURE THE NEW DATASET HAS ALL THE COLUMNS?
dtm_Predictions <- predict(model, new_data = modeling_reviews_dtm, type = 'class')

dataTest <- as.data.frame(1)
range_write(ss, data = dataTest, range = "C5", col_names = FALSE)

```

